version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dbfinalapp
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"  # ✅ ใช้พอร์ตปกติใน container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - USE_DOCKER=true
      - DB_NAME=dbfinalapp
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_PORT=3306   # <<< ต้องเป็น 3306


volumes:
  mysql_data:
