version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # External:Internal

  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for db...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'DB is up!' &&
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 finalpj.wsgi:application
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always  # แนะนำให้ใส่ใน production

volumes:
  postgres_data:
