version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        while ! nc -z db 3306; do sleep 1; done &&
        echo 'MySQL is up!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
